[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
ansi_term = "0.12.1"
regex = "1.5.4"
indoc = "1.0.3"

[dev-dependencies]
rstest = "0.11.0"